=== api-evangelist/amazon-inspector/json-schema/inspector-lambda-layer-aggregation-response-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/api-evangelist/amazon-inspector/refs/heads/main/json-schema/inspector-lambda-layer-aggregation-response-schema.json",
  "title": "LambdaLayerAggregationResponse",
  "description": "A response that contains the results of an AWS Lambda function layer finding aggregation.",
  "type": "object",
  "properties": {
    "accountId": {
      "allOf": [
        {
          "$ref": "#/components/schemas/AccountId"
        },
        {
          "description": "The account ID of the AWS Lambda function layer."
        }
      ]
    },
    "functionName": {
      "allOf": [
        {
          "$ref": "#/components/schemas/NonEmptyString"
        },
        {
          "description": "The names of the AWS Lambda functions associated with the layers."
        }
      ]
    },
    "layerArn": {
      "allOf": [
        {
          "$ref": "#/components/schemas/NonEmptyString"
        },
        {
          "description": "The Amazon Resource Name (ARN) of the AWS Lambda function layer."
        }
      ]
    },
    "resourceId": {
      "allOf": [
        {
          "$ref": "#/components/schemas/NonEmptyString"
        },
        {
          "description": "The Resource ID of the AWS Lambda function layer."
        }
      ]
    },
    "severityCounts": {
      "type": "object",
      "properties": {
        "all": {
          "allOf": [
            {
              "$ref": "#/components/schemas/Long"
            },
            {
              "description": "The total count of findings from all severities."
            }
          ]
        },
        "critical": {
          "allOf": [
            {
              "$ref": "#/components/schemas/Long"
            },
            {
              "description": "The total count of critical severity findings."
            }
          ]
        },
        "high": {
          "allOf": [
            {
              "$ref": "#/components/schemas/Long"
            },
            {
              "description": "The total count of high severity findings."
            }
          ]
        },
        "medium": {
          "allOf": [
            {
              "$ref": "#/components/schemas/Long"
            },
            {
              "description": "The total count of medium severity findings."
            }
          ]
        }
      },
      "description": "An object that contains the counts of aggregated finding per severity."
    }
  },
  "required": [
    "accountId",
    "functionName",
    "layerArn",
    "resourceId"
  ]
}

=== api-evangelist/amazon-inspector/examples/inspector-lambda-layer-aggregation-response-example.json
{
  "accountId": "id-abc123",
  "functionName": "example-resource",
  "layerArn": "arn:aws:iot:us-east-1:123456789012:thing/example",
  "resourceId": "id-abc123",
  "severityCounts": {
    "all": "example-value",
    "critical": "example-value",
    "high": "example-value",
    "medium": "example-value"
  }
}
